//go:build ignore

package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"sort"
	"strings"
)

const baseURL = "https://nekos.best/api/v2/"

type Endpoint struct {
	Format string `json:"format"`
}

func main() {
	req, err := http.NewRequest("GET", baseURL+"endpoints", nil)
	if err != nil {
		panic(err)
	}
	req.Header.Set("User-Agent", "gubi-go-generator/1.0 (github.com/yd4dev/gubi)")

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		panic(err)
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		panic(err)
	}

	var endpoints map[string]Endpoint
	if err := json.Unmarshal(body, &endpoints); err != nil {
		panic(err)
	}

	var images, gifs []string
	for name, details := range endpoints {
		switch details.Format {
		case "png":
			images = append(images, name)
		case "gif":
			gifs = append(gifs, name)
		}
	}

	// Sort to ensure deterministic output (important for code generation!)
	sort.Strings(images)
	sort.Strings(gifs)

	// Create or overwrite the generated file
	out, err := os.Create("types.go")
	if err != nil {
		panic(err)
	}
	defer out.Close()

	// Write the file header
	fmt.Fprintln(out, "// Code generated by genCategories.go; DO NOT EDIT.")
	fmt.Fprintln(out, "package nekosbest")

	fmt.Fprintln(out, "type imageCategory string")
	fmt.Fprintln(out, "const (")
	for _, item := range images {
		fmt.Fprintf(out, "\t%s imageCategory = \"%s\"\n", strings.ToUpper(item[:1])+item[1:], item)
	}
	fmt.Fprintln(out, ")")

	fmt.Fprintln(out, "type gifCategory string")
	fmt.Fprintln(out, "const (")
	for _, item := range gifs {
		fmt.Fprintf(out, "\t%s gifCategory = \"%s\"\n", strings.ToUpper(item[:1])+item[1:], item)
	}
	fmt.Fprintln(out, ")")

	fmt.Println("Successfully generated types.go")
}
